//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://10.4.2.33/ca-server/webservices/ondemandcontent")]
        public string MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_ConaxContegoOnDemandContentService_OnDemandContentWebService {
            get {
                return ((string)(this["MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_ConaxContegoOnDemandContentService_On" +
                    "DemandContentWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://10.4.2.33/ca-server/webservices/ppvproduct")]
        public string MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_ConaxContegoPPVProductService_PpvProductWebService {
            get {
                return ((string)(this["MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_ConaxContegoPPVProductService_PpvProd" +
                    "uctWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/IS/ContentService.asmx")]
        public string MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_ContentService_ContentService {
            get {
                return ((string)(this["MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_ContentService_ContentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/integrationservices/serviceservice.asmx")]
        public string MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_ServiceService_ServiceService {
            get {
                return ((string)(this["MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_ServiceService_ServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/integrationservices/mppuserservice.asmx")]
        public string MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_MPPUserService_MPPUserService {
            get {
                return ((string)(this["MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_MPPUserService_MPPUserService"]));
            }
        }
    }
}
