//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.MPPUserService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MPPUserServiceSoap", Namespace="http://tempuri.org/")]
    public partial class MPPUserService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenticateMPPUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMPPUserAccountInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMPPUserAccountInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MPPUserService() {
            this.Url = global::MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Properties.Settings.Default.MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_MPPUserService_MPPUserService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenticateMPPUserCompletedEventHandler AuthenticateMPPUserCompleted;
        
        /// <remarks/>
        public event GetMPPUserAccountInfoCompletedEventHandler GetMPPUserAccountInfoCompleted;
        
        /// <remarks/>
        public event UpdateMPPUserAccountInfoCompletedEventHandler UpdateMPPUserAccountInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateMPPUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AuthenticateMPPUser(string userName, string password) {
            object[] results = this.Invoke("AuthenticateMPPUser", new object[] {
                        userName,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateMPPUserAsync(string userName, string password) {
            this.AuthenticateMPPUserAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateMPPUserAsync(string userName, string password, object userState) {
            if ((this.AuthenticateMPPUserOperationCompleted == null)) {
                this.AuthenticateMPPUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateMPPUserOperationCompleted);
            }
            this.InvokeAsync("AuthenticateMPPUser", new object[] {
                        userName,
                        password}, this.AuthenticateMPPUserOperationCompleted, userState);
        }
        
        private void OnAuthenticateMPPUserOperationCompleted(object arg) {
            if ((this.AuthenticateMPPUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateMPPUserCompleted(this, new AuthenticateMPPUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMPPUserAccountInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMPPUserAccountInfo(string accountId) {
            object[] results = this.Invoke("GetMPPUserAccountInfo", new object[] {
                        accountId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMPPUserAccountInfoAsync(string accountId) {
            this.GetMPPUserAccountInfoAsync(accountId, null);
        }
        
        /// <remarks/>
        public void GetMPPUserAccountInfoAsync(string accountId, object userState) {
            if ((this.GetMPPUserAccountInfoOperationCompleted == null)) {
                this.GetMPPUserAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMPPUserAccountInfoOperationCompleted);
            }
            this.InvokeAsync("GetMPPUserAccountInfo", new object[] {
                        accountId}, this.GetMPPUserAccountInfoOperationCompleted, userState);
        }
        
        private void OnGetMPPUserAccountInfoOperationCompleted(object arg) {
            if ((this.GetMPPUserAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMPPUserAccountInfoCompleted(this, new GetMPPUserAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateMPPUserAccountInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateMPPUserAccountInfo(string accountId, string MPPUserInfoXML) {
            object[] results = this.Invoke("UpdateMPPUserAccountInfo", new object[] {
                        accountId,
                        MPPUserInfoXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMPPUserAccountInfoAsync(string accountId, string MPPUserInfoXML) {
            this.UpdateMPPUserAccountInfoAsync(accountId, MPPUserInfoXML, null);
        }
        
        /// <remarks/>
        public void UpdateMPPUserAccountInfoAsync(string accountId, string MPPUserInfoXML, object userState) {
            if ((this.UpdateMPPUserAccountInfoOperationCompleted == null)) {
                this.UpdateMPPUserAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMPPUserAccountInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateMPPUserAccountInfo", new object[] {
                        accountId,
                        MPPUserInfoXML}, this.UpdateMPPUserAccountInfoOperationCompleted, userState);
        }
        
        private void OnUpdateMPPUserAccountInfoOperationCompleted(object arg) {
            if ((this.UpdateMPPUserAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMPPUserAccountInfoCompleted(this, new UpdateMPPUserAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthenticateMPPUserCompletedEventHandler(object sender, AuthenticateMPPUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateMPPUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateMPPUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMPPUserAccountInfoCompletedEventHandler(object sender, GetMPPUserAccountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMPPUserAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMPPUserAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateMPPUserAccountInfoCompletedEventHandler(object sender, UpdateMPPUserAccountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMPPUserAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMPPUserAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591