//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.ConaxContegoOnDemandContentService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OnDemandContentServiceSoapBinding", Namespace="http://www.conax.com/cas/wsdl/ondemand-content/v1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractResponseType))]
    public partial class OnDemandContentWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateOnDemandContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOnDemandContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDvbAccessCriteriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOnDemandContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveOnDemandContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OnDemandContentWebService() {
            this.Url = global::MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Properties.Settings.Default.MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_ConaxContegoOnDemandContentService_OnDemandContentWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateOnDemandContentCompletedEventHandler CreateOnDemandContentCompleted;
        
        /// <remarks/>
        public event GetOnDemandContentCompletedEventHandler GetOnDemandContentCompleted;
        
        /// <remarks/>
        public event GetDvbAccessCriteriaCompletedEventHandler GetDvbAccessCriteriaCompleted;
        
        /// <remarks/>
        public event UpdateOnDemandContentCompletedEventHandler UpdateOnDemandContentCompleted;
        
        /// <remarks/>
        public event RemoveOnDemandContentCompletedEventHandler RemoveOnDemandContentCompleted;
        
        /// <remarks/>
        public event GetInfoCompletedEventHandler GetInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("OnDemandContentUpdateResponse")]
        public OnDemandContentResponseType CreateOnDemandContent(OnDemandContentUpdateRequestType CreateOnDemandContentRequest) {
            object[] results = this.Invoke("CreateOnDemandContent", new object[] {
                        CreateOnDemandContentRequest});
            return ((OnDemandContentResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOnDemandContentAsync(OnDemandContentUpdateRequestType CreateOnDemandContentRequest) {
            this.CreateOnDemandContentAsync(CreateOnDemandContentRequest, null);
        }
        
        /// <remarks/>
        public void CreateOnDemandContentAsync(OnDemandContentUpdateRequestType CreateOnDemandContentRequest, object userState) {
            if ((this.CreateOnDemandContentOperationCompleted == null)) {
                this.CreateOnDemandContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOnDemandContentOperationCompleted);
            }
            this.InvokeAsync("CreateOnDemandContent", new object[] {
                        CreateOnDemandContentRequest}, this.CreateOnDemandContentOperationCompleted, userState);
        }
        
        private void OnCreateOnDemandContentOperationCompleted(object arg) {
            if ((this.CreateOnDemandContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOnDemandContentCompleted(this, new CreateOnDemandContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("OnDemandContentUpdateResponse")]
        public OnDemandContentResponseType GetOnDemandContent(OnDemandContentIdRequestType GetOnDemandContentRequest) {
            object[] results = this.Invoke("GetOnDemandContent", new object[] {
                        GetOnDemandContentRequest});
            return ((OnDemandContentResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetOnDemandContentAsync(OnDemandContentIdRequestType GetOnDemandContentRequest) {
            this.GetOnDemandContentAsync(GetOnDemandContentRequest, null);
        }
        
        /// <remarks/>
        public void GetOnDemandContentAsync(OnDemandContentIdRequestType GetOnDemandContentRequest, object userState) {
            if ((this.GetOnDemandContentOperationCompleted == null)) {
                this.GetOnDemandContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOnDemandContentOperationCompleted);
            }
            this.InvokeAsync("GetOnDemandContent", new object[] {
                        GetOnDemandContentRequest}, this.GetOnDemandContentOperationCompleted, userState);
        }
        
        private void OnGetOnDemandContentOperationCompleted(object arg) {
            if ((this.GetOnDemandContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOnDemandContentCompleted(this, new GetOnDemandContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetDvbAccessCriteriaResponse")]
        public DvbAccessCriteriaResponseType GetDvbAccessCriteria(OnDemandContentIdRequestType GetDvbAccessCriteriaRequest) {
            object[] results = this.Invoke("GetDvbAccessCriteria", new object[] {
                        GetDvbAccessCriteriaRequest});
            return ((DvbAccessCriteriaResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDvbAccessCriteriaAsync(OnDemandContentIdRequestType GetDvbAccessCriteriaRequest) {
            this.GetDvbAccessCriteriaAsync(GetDvbAccessCriteriaRequest, null);
        }
        
        /// <remarks/>
        public void GetDvbAccessCriteriaAsync(OnDemandContentIdRequestType GetDvbAccessCriteriaRequest, object userState) {
            if ((this.GetDvbAccessCriteriaOperationCompleted == null)) {
                this.GetDvbAccessCriteriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDvbAccessCriteriaOperationCompleted);
            }
            this.InvokeAsync("GetDvbAccessCriteria", new object[] {
                        GetDvbAccessCriteriaRequest}, this.GetDvbAccessCriteriaOperationCompleted, userState);
        }
        
        private void OnGetDvbAccessCriteriaOperationCompleted(object arg) {
            if ((this.GetDvbAccessCriteriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDvbAccessCriteriaCompleted(this, new GetDvbAccessCriteriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("OnDemandContentUpdateResponse")]
        public OnDemandContentResponseType UpdateOnDemandContent(OnDemandContentUpdateRequestType UpdateOnDemandContentRequest) {
            object[] results = this.Invoke("UpdateOnDemandContent", new object[] {
                        UpdateOnDemandContentRequest});
            return ((OnDemandContentResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOnDemandContentAsync(OnDemandContentUpdateRequestType UpdateOnDemandContentRequest) {
            this.UpdateOnDemandContentAsync(UpdateOnDemandContentRequest, null);
        }
        
        /// <remarks/>
        public void UpdateOnDemandContentAsync(OnDemandContentUpdateRequestType UpdateOnDemandContentRequest, object userState) {
            if ((this.UpdateOnDemandContentOperationCompleted == null)) {
                this.UpdateOnDemandContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOnDemandContentOperationCompleted);
            }
            this.InvokeAsync("UpdateOnDemandContent", new object[] {
                        UpdateOnDemandContentRequest}, this.UpdateOnDemandContentOperationCompleted, userState);
        }
        
        private void OnUpdateOnDemandContentOperationCompleted(object arg) {
            if ((this.UpdateOnDemandContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOnDemandContentCompleted(this, new UpdateOnDemandContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("OnDemandContentResponse")]
        public OnDemandContentResponseType RemoveOnDemandContent(RemoveOnDemandContentRequestType RemoveOnDemandContentRequest) {
            object[] results = this.Invoke("RemoveOnDemandContent", new object[] {
                        RemoveOnDemandContentRequest});
            return ((OnDemandContentResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveOnDemandContentAsync(RemoveOnDemandContentRequestType RemoveOnDemandContentRequest) {
            this.RemoveOnDemandContentAsync(RemoveOnDemandContentRequest, null);
        }
        
        /// <remarks/>
        public void RemoveOnDemandContentAsync(RemoveOnDemandContentRequestType RemoveOnDemandContentRequest, object userState) {
            if ((this.RemoveOnDemandContentOperationCompleted == null)) {
                this.RemoveOnDemandContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveOnDemandContentOperationCompleted);
            }
            this.InvokeAsync("RemoveOnDemandContent", new object[] {
                        RemoveOnDemandContentRequest}, this.RemoveOnDemandContentOperationCompleted, userState);
        }
        
        private void OnRemoveOnDemandContentOperationCompleted(object arg) {
            if ((this.RemoveOnDemandContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveOnDemandContentCompleted(this, new RemoveOnDemandContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ondemand-content/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("InfoResponse", Namespace="http://www.conax.com/cas/xsd/common-types/v1")]
        public InfoResponseType GetInfo() {
            object[] results = this.Invoke("GetInfo", new object[0]);
            return ((InfoResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoAsync() {
            this.GetInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetInfoAsync(object userState) {
            if ((this.GetInfoOperationCompleted == null)) {
                this.GetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoOperationCompleted);
            }
            this.InvokeAsync("GetInfo", new object[0], this.GetInfoOperationCompleted, userState);
        }
        
        private void OnGetInfoOperationCompleted(object arg) {
            if ((this.GetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoCompleted(this, new GetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ondemand-content/v1")]
    public partial class OnDemandContentUpdateRequestType {
        
        private OnDemandContentType onDemandContentField;
        
        /// <remarks/>
        public OnDemandContentType OnDemandContent {
            get {
                return this.onDemandContentField;
            }
            set {
                this.onDemandContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ondemand-content/v1")]
    public partial class OnDemandContentType {
        
        private string contentIdField;
        
        private string nameField;
        
        private string descriptionField;
        
        private int[] offeredByField;
        
        private System.DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private string freeAccessField;
        
        private string maturityRatingField;
        
        private string uRIProfileField;
        
        private BroadcastParameterType broadcastParamsField;
        
        private OttParameterType ottParamsField;
        
        /// <remarks/>
        public string ContentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProductId", IsNullable=false)]
        public int[] OfferedBy {
            get {
                return this.offeredByField;
            }
            set {
                this.offeredByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateSpecified {
            get {
                return this.expiryDateFieldSpecified;
            }
            set {
                this.expiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string FreeAccess {
            get {
                return this.freeAccessField;
            }
            set {
                this.freeAccessField = value;
            }
        }
        
        /// <remarks/>
        public string MaturityRating {
            get {
                return this.maturityRatingField;
            }
            set {
                this.maturityRatingField = value;
            }
        }
        
        /// <remarks/>
        public string URIProfile {
            get {
                return this.uRIProfileField;
            }
            set {
                this.uRIProfileField = value;
            }
        }
        
        /// <remarks/>
        public BroadcastParameterType BroadcastParams {
            get {
                return this.broadcastParamsField;
            }
            set {
                this.broadcastParamsField = value;
            }
        }
        
        /// <remarks/>
        public OttParameterType OttParams {
            get {
                return this.ottParamsField;
            }
            set {
                this.ottParamsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ondemand-content/v1")]
    public partial class BroadcastParameterType {
        
        private BridgeControlType bridgeControlField;
        
        private string pairingEnforcementField;
        
        /// <remarks/>
        public BridgeControlType BridgeControl {
            get {
                return this.bridgeControlField;
            }
            set {
                this.bridgeControlField = value;
            }
        }
        
        /// <remarks/>
        public string PairingEnforcement {
            get {
                return this.pairingEnforcementField;
            }
            set {
                this.pairingEnforcementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/content-common-types/v1")]
    public partial class BridgeControlType {
        
        private SecurityDomainType[] exportToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SecurityDomain", IsNullable=false)]
        public SecurityDomainType[] ExportTo {
            get {
                return this.exportToField;
            }
            set {
                this.exportToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/content-common-types/v1")]
    public partial class SecurityDomainType {
        
        private string nameField;
        
        private PropertyType[] exportConditionsField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
        public PropertyType[] ExportConditions {
            get {
                return this.exportConditionsField;
            }
            set {
                this.exportConditionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/content-common-types/v1")]
    public partial class PropertyType {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/common-types/v1")]
    public partial class InfoResponseType {
        
        private string infoField;
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ondemand-content/v1")]
    public partial class RemoveOnDemandContentRequestType {
        
        private string contentIdField;
        
        /// <remarks/>
        public string ContentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ondemand-content/v1")]
    public partial class OnDemandContentIdRequestType {
        
        private string contentIdField;
        
        /// <remarks/>
        public string ContentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ondemand-content/v1")]
    public partial class DvbAccessCriteriaType {
        
        private byte[] dataField;
        
        private string descriptionField;
        
        private System.DateTime regTimeField;
        
        private bool regTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RegTime {
            get {
                return this.regTimeField;
            }
            set {
                this.regTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegTimeSpecified {
            get {
                return this.regTimeFieldSpecified;
            }
            set {
                this.regTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/common-types/v1")]
    public partial class TransactionStatusType {
        
        private string statusCodeField;
        
        private string messageField;
        
        private string transactionIdField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OnDemandContentResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DvbAccessCriteriaResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/common-types/v1")]
    public abstract partial class AbstractResponseType {
        
        private TransactionStatusType transactionStatusField;
        
        /// <remarks/>
        public TransactionStatusType TransactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ondemand-content/v1")]
    public partial class OnDemandContentResponseType : AbstractResponseType {
        
        private OnDemandContentType onDemandContentField;
        
        /// <remarks/>
        public OnDemandContentType OnDemandContent {
            get {
                return this.onDemandContentField;
            }
            set {
                this.onDemandContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ondemand-content/v1")]
    public partial class DvbAccessCriteriaResponseType : AbstractResponseType {
        
        private DvbAccessCriteriaType dvbAccessCriteriaField;
        
        /// <remarks/>
        public DvbAccessCriteriaType DvbAccessCriteria {
            get {
                return this.dvbAccessCriteriaField;
            }
            set {
                this.dvbAccessCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ondemand-content/v1")]
    public partial class OttParameterType {
        
        private string ottDeviceProfileField;
        
        /// <remarks/>
        public string OttDeviceProfile {
            get {
                return this.ottDeviceProfileField;
            }
            set {
                this.ottDeviceProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateOnDemandContentCompletedEventHandler(object sender, CreateOnDemandContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOnDemandContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOnDemandContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OnDemandContentResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OnDemandContentResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOnDemandContentCompletedEventHandler(object sender, GetOnDemandContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOnDemandContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOnDemandContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OnDemandContentResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OnDemandContentResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDvbAccessCriteriaCompletedEventHandler(object sender, GetDvbAccessCriteriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDvbAccessCriteriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDvbAccessCriteriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DvbAccessCriteriaResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DvbAccessCriteriaResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateOnDemandContentCompletedEventHandler(object sender, UpdateOnDemandContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOnDemandContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOnDemandContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OnDemandContentResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OnDemandContentResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RemoveOnDemandContentCompletedEventHandler(object sender, RemoveOnDemandContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveOnDemandContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveOnDemandContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OnDemandContentResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OnDemandContentResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetInfoCompletedEventHandler(object sender, GetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InfoResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InfoResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591