//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:envivio:balancer:1.0", ConfigurationName="Envivio.ServicePortType")]
    public interface ServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envivio:balancer:1.0/addResource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resourceid")]
        string addResource(MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.resource resource);
        
        // CODEGEN: Parameter 'resources' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:envivio:balancer:1.0/getAllResources", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resources")]
        MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getAllResourcesResponse getAllResources(MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getAllResourcesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envivio:balancer:1.0/removeResource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void removeResource(string resourceid);
        
        // CODEGEN: Parameter 'jobparams' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:envivio:balancer:1.0/launchJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="jobid")]
        MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.launchJobResponse launchJob(MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.launchJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envivio:balancer:1.0/cancelJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void cancelJob(string jobid);
        
        // CODEGEN: Parameter 'infos' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:envivio:balancer:1.0/getJobStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="state")]
        MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStatusResponse getJobStatus(MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envivio:balancer:1.0/getStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string getStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envivio:balancer:1.0/start", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void start();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:envivio:balancer:1.0/stop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void stop();
        
        // CODEGEN: Parameter 'states' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:envivio:balancer:1.0/getJobStatusSummary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="states")]
        MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStateSummaryResponse getJobStateSummary(MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStateSummaryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:envivio:balancer:1.0")]
    public partial class resource : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string urlField;
        
        private string typeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:envivio:balancer:1.0")]
    public partial class jobstatesummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int countField;
        
        private bool countFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:envivio:balancer:1.0")]
    public partial class jobstatusinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:envivio:balancer:1.0")]
    public partial class param : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResources", WrapperNamespace="urn:envivio:balancer:1.0", IsWrapped=true)]
    public partial class getAllResourcesRequest {
        
        public getAllResourcesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResourcesResponse", WrapperNamespace="urn:envivio:balancer:1.0", IsWrapped=true)]
    public partial class getAllResourcesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public resource[] resources;
        
        public getAllResourcesResponse() {
        }
        
        public getAllResourcesResponse(resource[] resources) {
            this.resources = resources;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="launchJob", WrapperNamespace="urn:envivio:balancer:1.0", IsWrapped=true)]
    public partial class launchJobRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string presetid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public param[] jobparams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string jobname;
        
        public launchJobRequest() {
        }
        
        public launchJobRequest(string presetid, param[] jobparams, string jobname) {
            this.presetid = presetid;
            this.jobparams = jobparams;
            this.jobname = jobname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="launchJobResponse", WrapperNamespace="urn:envivio:balancer:1.0", IsWrapped=true)]
    public partial class launchJobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string jobid;
        
        public launchJobResponse() {
        }
        
        public launchJobResponse(string jobid) {
            this.jobid = jobid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJobStatus", WrapperNamespace="urn:envivio:balancer:1.0", IsWrapped=true)]
    public partial class getJobStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string jobid;
        
        public getJobStatusRequest() {
        }
        
        public getJobStatusRequest(string jobid) {
            this.jobid = jobid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJobStatusResponse", WrapperNamespace="urn:envivio:balancer:1.0", IsWrapped=true)]
    public partial class getJobStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("info", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public jobstatusinfo[] infos;
        
        public getJobStatusResponse() {
        }
        
        public getJobStatusResponse(string state, jobstatusinfo[] infos) {
            this.state = state;
            this.infos = infos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJobStateSummary", WrapperNamespace="urn:envivio:balancer:1.0", IsWrapped=true)]
    public partial class getJobStateSummaryRequest {
        
        public getJobStateSummaryRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJobStateSummaryResponse", WrapperNamespace="urn:envivio:balancer:1.0", IsWrapped=true)]
    public partial class getJobStateSummaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("state", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public jobstatesummary[] states;
        
        public getJobStateSummaryResponse() {
        }
        
        public getJobStateSummaryResponse(jobstatesummary[] states) {
            this.states = states;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicePortTypeChannel : MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePortTypeClient : System.ServiceModel.ClientBase<MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType>, MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType {
        
        public ServicePortTypeClient() {
        }
        
        public ServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addResource(MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.resource resource) {
            return base.Channel.addResource(resource);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getAllResourcesResponse MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType.getAllResources(MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getAllResourcesRequest request) {
            return base.Channel.getAllResources(request);
        }
        
        public resource[] getAllResources() {
            MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getAllResourcesRequest inValue = new MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getAllResourcesRequest();
            MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getAllResourcesResponse retVal = ((MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType)(this)).getAllResources(inValue);
            return retVal.resources;
        }
        
        public void removeResource(string resourceid) {
            base.Channel.removeResource(resourceid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.launchJobResponse MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType.launchJob(MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.launchJobRequest request) {
            return base.Channel.launchJob(request);
        }
        
        public string launchJob(string presetid, param[] jobparams, string jobname) {
            MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.launchJobRequest inValue = new MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.launchJobRequest();
            inValue.presetid = presetid;
            inValue.jobparams = jobparams;
            inValue.jobname = jobname;
            MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.launchJobResponse retVal = ((MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType)(this)).launchJob(inValue);
            return retVal.jobid;
        }
        
        public void cancelJob(string jobid) {
            base.Channel.cancelJob(jobid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStatusResponse MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType.getJobStatus(MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStatusRequest request) {
            return base.Channel.getJobStatus(request);
        }
        
        public string getJobStatus(string jobid, out jobstatusinfo[] infos) {
            MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStatusRequest inValue = new MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStatusRequest();
            inValue.jobid = jobid;
            MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStatusResponse retVal = ((MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType)(this)).getJobStatus(inValue);
            infos = retVal.infos;
            return retVal.state;
        }
        
        public string getStatus() {
            return base.Channel.getStatus();
        }
        
        public void start() {
            base.Channel.start();
        }
        
        public void stop() {
            base.Channel.stop();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStateSummaryResponse MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType.getJobStateSummary(MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStateSummaryRequest request) {
            return base.Channel.getJobStateSummary(request);
        }
        
        public jobstatesummary[] getJobStateSummary() {
            MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStateSummaryRequest inValue = new MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStateSummaryRequest();
            MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.getJobStateSummaryResponse retVal = ((MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Envivio.ServicePortType)(this)).getJobStateSummary(inValue);
            return retVal.states;
        }
    }
}
