//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.ConaxContegoPPVProductService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PpvProductServiceSoapBinding", Namespace="http://www.conax.com/cas/wsdl/ppvproduct/v1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractResponseType))]
    public partial class PpvProductWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreatePpvProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePpvProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemovePpvProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPpvProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PpvProductWebService() {
            this.Url = global::MPS.MPP.Auxiliary.ConaxWorkflowManager.Core.Properties.Settings.Default.MPS_MPP_Auxiliary_ConaxWorkflowManager_Core_ConaxContegoPPVProductService_PpvProductWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreatePpvProductCompletedEventHandler CreatePpvProductCompleted;
        
        /// <remarks/>
        public event UpdatePpvProductCompletedEventHandler UpdatePpvProductCompleted;
        
        /// <remarks/>
        public event RemovePpvProductCompletedEventHandler RemovePpvProductCompleted;
        
        /// <remarks/>
        public event GetPpvProductCompletedEventHandler GetPpvProductCompleted;
        
        /// <remarks/>
        public event GetInfoCompletedEventHandler GetInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ppvproduct/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ppvproduct/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PpvProductResponse")]
        public PpvProductResponseType CreatePpvProduct(PpvProductUpdateRequestType CreatePpvProductRequest) {
            object[] results = this.Invoke("CreatePpvProduct", new object[] {
                        CreatePpvProductRequest});
            return ((PpvProductResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePpvProductAsync(PpvProductUpdateRequestType CreatePpvProductRequest) {
            this.CreatePpvProductAsync(CreatePpvProductRequest, null);
        }
        
        /// <remarks/>
        public void CreatePpvProductAsync(PpvProductUpdateRequestType CreatePpvProductRequest, object userState) {
            if ((this.CreatePpvProductOperationCompleted == null)) {
                this.CreatePpvProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePpvProductOperationCompleted);
            }
            this.InvokeAsync("CreatePpvProduct", new object[] {
                        CreatePpvProductRequest}, this.CreatePpvProductOperationCompleted, userState);
        }
        
        private void OnCreatePpvProductOperationCompleted(object arg) {
            if ((this.CreatePpvProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePpvProductCompleted(this, new CreatePpvProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ppvproduct/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ppvproduct/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PpvProductResponse")]
        public PpvProductResponseType UpdatePpvProduct(PpvProductUpdateRequestType UpdatePpvProductRequest) {
            object[] results = this.Invoke("UpdatePpvProduct", new object[] {
                        UpdatePpvProductRequest});
            return ((PpvProductResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePpvProductAsync(PpvProductUpdateRequestType UpdatePpvProductRequest) {
            this.UpdatePpvProductAsync(UpdatePpvProductRequest, null);
        }
        
        /// <remarks/>
        public void UpdatePpvProductAsync(PpvProductUpdateRequestType UpdatePpvProductRequest, object userState) {
            if ((this.UpdatePpvProductOperationCompleted == null)) {
                this.UpdatePpvProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePpvProductOperationCompleted);
            }
            this.InvokeAsync("UpdatePpvProduct", new object[] {
                        UpdatePpvProductRequest}, this.UpdatePpvProductOperationCompleted, userState);
        }
        
        private void OnUpdatePpvProductOperationCompleted(object arg) {
            if ((this.UpdatePpvProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePpvProductCompleted(this, new UpdatePpvProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ppvproduct/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ppvproduct/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PpvProductResponse")]
        public PpvProductResponseType RemovePpvProduct(RemovePpvProductRequestType RemovePpvProductRequest) {
            object[] results = this.Invoke("RemovePpvProduct", new object[] {
                        RemovePpvProductRequest});
            return ((PpvProductResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void RemovePpvProductAsync(RemovePpvProductRequestType RemovePpvProductRequest) {
            this.RemovePpvProductAsync(RemovePpvProductRequest, null);
        }
        
        /// <remarks/>
        public void RemovePpvProductAsync(RemovePpvProductRequestType RemovePpvProductRequest, object userState) {
            if ((this.RemovePpvProductOperationCompleted == null)) {
                this.RemovePpvProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemovePpvProductOperationCompleted);
            }
            this.InvokeAsync("RemovePpvProduct", new object[] {
                        RemovePpvProductRequest}, this.RemovePpvProductOperationCompleted, userState);
        }
        
        private void OnRemovePpvProductOperationCompleted(object arg) {
            if ((this.RemovePpvProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemovePpvProductCompleted(this, new RemovePpvProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ppvproduct/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ppvproduct/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PpvProductResponse")]
        public PpvProductResponseType GetPpvProduct(GetPpvProductRequestType GetPpvProductRequest) {
            object[] results = this.Invoke("GetPpvProduct", new object[] {
                        GetPpvProductRequest});
            return ((PpvProductResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetPpvProductAsync(GetPpvProductRequestType GetPpvProductRequest) {
            this.GetPpvProductAsync(GetPpvProductRequest, null);
        }
        
        /// <remarks/>
        public void GetPpvProductAsync(GetPpvProductRequestType GetPpvProductRequest, object userState) {
            if ((this.GetPpvProductOperationCompleted == null)) {
                this.GetPpvProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPpvProductOperationCompleted);
            }
            this.InvokeAsync("GetPpvProduct", new object[] {
                        GetPpvProductRequest}, this.GetPpvProductOperationCompleted, userState);
        }
        
        private void OnGetPpvProductOperationCompleted(object arg) {
            if ((this.GetPpvProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPpvProductCompleted(this, new GetPpvProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.conax.com/cas/xsd/ppvproduct/v1", ResponseNamespace="http://www.conax.com/cas/xsd/ppvproduct/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("InfoResponse", Namespace="http://www.conax.com/cas/xsd/common-types/v1")]
        public InfoResponseType GetInfo() {
            object[] results = this.Invoke("GetInfo", new object[0]);
            return ((InfoResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoAsync() {
            this.GetInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetInfoAsync(object userState) {
            if ((this.GetInfoOperationCompleted == null)) {
                this.GetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoOperationCompleted);
            }
            this.InvokeAsync("GetInfo", new object[0], this.GetInfoOperationCompleted, userState);
        }
        
        private void OnGetInfoOperationCompleted(object arg) {
            if ((this.GetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoCompleted(this, new GetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ppvproduct/v1")]
    public partial class PpvProductUpdateRequestType {
        
        private PpvProductType ppvProductField;
        
        /// <remarks/>
        public PpvProductType PpvProduct {
            get {
                return this.ppvProductField;
            }
            set {
                this.ppvProductField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RentalPpvProductType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventPpvProductType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ppvproduct/v1")]
    public abstract partial class PpvProductType {
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private string nameField;
        
        private int emmPlayoutDurationInHoursField;
        
        private bool emmPlayoutDurationInHoursFieldSpecified;
        
        private ProductLabelType[] localizedProductLabelsField;
        
        private PriceType[] localizedPricesField;
        
        private string[] excludedForSmsesField;
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int EmmPlayoutDurationInHours {
            get {
                return this.emmPlayoutDurationInHoursField;
            }
            set {
                this.emmPlayoutDurationInHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmmPlayoutDurationInHoursSpecified {
            get {
                return this.emmPlayoutDurationInHoursFieldSpecified;
            }
            set {
                this.emmPlayoutDurationInHoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProductLabel", IsNullable=false)]
        public ProductLabelType[] LocalizedProductLabels {
            get {
                return this.localizedProductLabelsField;
            }
            set {
                this.localizedProductLabelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Price", IsNullable=false)]
        public PriceType[] LocalizedPrices {
            get {
                return this.localizedPricesField;
            }
            set {
                this.localizedPricesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SmsName", IsNullable=false)]
        public string[] ExcludedForSmses {
            get {
                return this.excludedForSmsesField;
            }
            set {
                this.excludedForSmsesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ppvproduct/v1")]
    public partial class ProductLabelType {
        
        private string productLabelField;
        
        private string languageCodeField;
        
        /// <remarks/>
        public string ProductLabel {
            get {
                return this.productLabelField;
            }
            set {
                this.productLabelField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/common-types/v1")]
    public partial class InfoResponseType {
        
        private string infoField;
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ppvproduct/v1")]
    public partial class GetPpvProductRequestType {
        
        private int productIdField;
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ppvproduct/v1")]
    public partial class RemovePpvProductRequestType {
        
        private int productIdField;
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/common-types/v1")]
    public partial class TransactionStatusType {
        
        private string statusCodeField;
        
        private string messageField;
        
        private string transactionIdField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PpvProductResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/common-types/v1")]
    public abstract partial class AbstractResponseType {
        
        private TransactionStatusType transactionStatusField;
        
        /// <remarks/>
        public TransactionStatusType TransactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ppvproduct/v1")]
    public partial class PpvProductResponseType : AbstractResponseType {
        
        private PpvProductType ppvProductField;
        
        /// <remarks/>
        public PpvProductType PpvProduct {
            get {
                return this.ppvProductField;
            }
            set {
                this.ppvProductField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ppvproduct/v1")]
    public partial class BroadcastPeriodType {
        
        private System.DateTime startField;
        
        private System.DateTime endField;
        
        /// <remarks/>
        public System.DateTime Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ppvproduct/v1")]
    public partial class PriceType {
        
        private double amountField;
        
        private string currencyCodeField;
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ppvproduct/v1")]
    public partial class RentalPpvProductType : PpvProductType {
        
        private int rentalTimeInMinutesField;
        
        private System.DateTime endOfLifeField;
        
        private bool endOfLifeFieldSpecified;
        
        /// <remarks/>
        public int RentalTimeInMinutes {
            get {
                return this.rentalTimeInMinutesField;
            }
            set {
                this.rentalTimeInMinutesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndOfLife {
            get {
                return this.endOfLifeField;
            }
            set {
                this.endOfLifeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndOfLifeSpecified {
            get {
                return this.endOfLifeFieldSpecified;
            }
            set {
                this.endOfLifeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conax.com/cas/xsd/ppvproduct/v1")]
    public partial class EventPpvProductType : PpvProductType {
        
        private BroadcastPeriodType broadcastPeriodField;
        
        /// <remarks/>
        public BroadcastPeriodType BroadcastPeriod {
            get {
                return this.broadcastPeriodField;
            }
            set {
                this.broadcastPeriodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreatePpvProductCompletedEventHandler(object sender, CreatePpvProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePpvProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePpvProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PpvProductResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PpvProductResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdatePpvProductCompletedEventHandler(object sender, UpdatePpvProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePpvProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePpvProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PpvProductResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PpvProductResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RemovePpvProductCompletedEventHandler(object sender, RemovePpvProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemovePpvProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemovePpvProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PpvProductResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PpvProductResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPpvProductCompletedEventHandler(object sender, GetPpvProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPpvProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPpvProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PpvProductResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PpvProductResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetInfoCompletedEventHandler(object sender, GetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InfoResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InfoResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591